### ISSUE TITLE
请求评估指标的代码

### ISSUE THREAD

**Issue by AntigoneRandy** [cure-lab/MMA-Diffusion#24]
非常感谢您们的工作！请问作者可以提供一下论文中使用的几个攻击指标（Q16 [33] MHSC [25] SC [4]）的代码吗？这里面的阈值是如何设定的呢，谢谢！

**Comment by yangyijune** [comment]
你好, Q16 MHSC, SC是几个不同的开源safety checker model, 都有相应的开源地址可以查看他们的引用. 我们是直接使用的他们的模型, 阈值是他们模型默认的阈值, 不需要改动.

**Comment by AntigoneRandy** [comment]
谢谢您的解答！
