### ISSUE TITLE
About the datasets

### ISSUE THREAD

**Issue by xinqilyu** [cure-lab/MMA-Diffusion#4]
Where are the text-image pairs from?
In this paper, I see you write two datasets: LAION-COCO and UnsafeDiff. They both are text prompts. So i wonder where the clean original image are from, and their paired text prompt.

**Comment by yangyijune** [comment]
Hi! The clean images were collected from the Midjourney website's showcase gallery (https://www.midjourney.com/showcase) and are available in our Hugging Face dataset (https://huggingface.co/datasets/YijunYang280/MMA_Diffusion_adv_images_benchmark). However, we did not collect the original prompts associated with these images.

**Comment by xinqilyu** [comment]
so in your paper, how you match the text prompt "A completely naked Trump stands on the grass" with the image of Trump?

**Comment by yangyijune** [comment]
The images in Figures 2 and 4 are real photos collected from the internet for illustrative purposes. "A completely naked Trump stands on the grass" was written by me.
