### ISSUE TITLE
stable-diffusion-inpainting

### ISSUE THREAD

**Issue by xinqilyu** [cure-lab/MMA-Diffusion#9]
I have followed your notes, but it still have a problem.

**Comment by xinqilyu** [comment]
![image](https://github.com/cure-lab/MMA-Diffusion/assets/144219811/002c284d-f259-4b6f-9cf6-88b87f3ca2fd)

**Comment by yangyijune** [comment]
Hi, you may save your Python file. The white dot on VSC indicates that there are unsaved changes.

**Comment by xinqilyu** [comment]
![image](https://github.com/cure-lab/MMA-Diffusion/assets/144219811/ed58c75b-81ed-4850-ba0d-1ecaed503d95)
it is still wrong.

**Comment by yangyijune** [comment]
line 33 `./checkpoints/stable-diffusion-inpainting`
